### ISSUE TITLE
Use timestamp of message as creation time for media files

### ISSUE THREAD

**Issue by arthurlutz** [russelldavies/matrix-archive#1]
First off : thank you *so* much for this project. I've been looking for a way to archive and extract family photos from our matrix e2e encrypted room for so long, it's so cool ! :star_struck: 

It would be awesome if there was an option (or as default) to create the media files with the creation time from the message timestamp. (exif dates can be used too).

**Comment by russelldavies** [comment]
You're welcome, I'm glad someone else has found it useful.

Regarding your feature request: would you also like the original filename stored somewhere or don't care for this information?

**Comment by arthurlutz** [comment]
The way the files are outputted right now (keeping the original filename) is great. Maybe at some point the use case of two different files with the same name will need to be handled (filename.png and filename(1).png like firefox does for example).

**Comment by russelldavies** [comment]
I misread your original request. I thought you meant you want the actual filename to be the timestamp, not the file's created attributes. Makes more sense. Good point about duplicate filenames, a file will be overwritten by a newer one if it has the same filename.
