### ISSUE TITLE
Save original events as JSON files

### ISSUE THREAD

**Issue by xaur** [russelldavies/matrix-archive#14]
I'd like to save all room's events in their original JSON representation instead of YAML.

A possible format would be one file per one day of events, where event objects are separated with newlines:

```
{obj1...}
{obj2...}
```

Advantages of this format:

- good interop with JSON tooling like jq and line-based processing like grep etc
- allows to render any format for viewing (html, txt, yaml etc)
- likely takes less space than yaml

**Comment by ColonisationCaptain** [comment]
This issue has been fixed in the latest commit.
