### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by r1bnc** [russelldavies/matrix-archive#30]
Does this still works?

**Comment by russelldavies** [comment]
I'm rewriting it (slowly) in Rust with changes to accommodate it being used as a non-interactive program but for manual archival tasks it works just fine still.

**Comment by r1bnc** [comment]
Thank you for your response, I would like to ask whether the `Rust` version would still produce the same output as this one?

**Comment by russelldavies** [comment]
I was going to change the format to JSON and have the output as similar to the Matrix event spec as possible but I'll include a script to convert back and forth from the present custom YAML format.

**Comment by jtrees** [comment]
Any update on this?

**Comment by dreamflasher** [comment]
@russelldavies are you still working on this? I'm looking for a way to have continuous backups.
