### ISSUE TITLE
Files with same filename will be overwritten

### ISSUE THREAD

**Issue by finefoot** [russelldavies/matrix-archive#5]
This has already been mentioned in #1. I just tested it and was able to verify the behavior as expected: If there are files attached to a room with the same filename, only one of those files will remain - the other one will be overwritten.

**Comment by russelldavies** [comment]
Fixed in commit 39add7d.

**Comment by finefoot** [comment]
:+1: Nice, thanks. Will try it out later.

**Comment by finefoot** [comment]
I noticed an issue with filenames without extension. Because in `f"{start} ({i}).{ext}"`, that `.` is going to be added no matter if `ext` is empty or not. However, there is a useful function `os.path.splitext`. I have added #11 to show what I'm using locally now, instead.

**Comment by finefoot** [comment]
You can choose to merge or reject the pull requests depending on how you feel about it. No hard feelings :blush: Thanks again for working on this :+1:
